### PR TITLE
Adding removeItem feature

### PR DESCRIPTION
**Pull request by ghost**
Adding the possibility to remove a key from the localstorage

### CODE REVIEW

**Comment by mfeckie** [comment]
Hey @bcecchinato, Thanks for the pull request.  This looks like a nice thing to have.

If you could add tests for what you're adding, I'd be happy to merge 😄

**Comment by ghost** [comment]
Sure I will make some more tests.

**Comment by ghost** [comment]
@mfeckie Tests added :)

**Comment by mfeckie** [comment]
Thanks @bcecchinato

**Pull request merged**
